# Home Assistant Configuration
home_assistant:
  url: "https://yslp.duckdns.org:8123"  # Home Assistant URL
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiY2QwOWZlNGNhNTc0ZWEyOTc1NWY3YzQxMjMzYzAwYyIsImlhdCI6MTc0NzE2OTQ4MSwiZXhwIjoyMDYyNTI5NDgxfQ.8oUZWfxzCllfy7HELGvSxd4jBdVjhNJKqXZ_CqwckXY"  # Long-lived access token
#  entity_id: "sensor.shellypro3em_34987a4627a4_total_active_power"  # Power consumption sensor entity ID
#  update_interval: 60  # Data collection interval in seconds
  entity_id: sensor.power_current_power"  # Power consumption sensor entity ID
  update_interval: 60  # Data collection interval in seconds


# Data Collection
data_collection:
  save_interval: 3600  # Save data every hour
  data_dir: "data/raw"  # Directory for raw data files
  max_samples: 10000  # Maximum number of samples to collect
  interval: 10  # Data collection interval in seconds

# Event Detection
event_detection:
  threshold: 20  # Minimum power change to consider as an event (Watts)
  min_peak_distance: 10  # Minimum samples between events
  window_size: 30  # Window size for event feature extraction

# NILM Model
nilm_model:
  n_appliances: 5  # Number of appliances to identify
  model_dir: "models"  # Directory for saved models

# Visualization
visualization:
  plot_dir: "plots"  # Directory for saved plots
  figure_size: [12, 8]  # Figure size in inches
  dpi: 100  # DPI for saved plots
  colors:
    power: "#1f77b4"  # Power consumption line color
    events: "#ff7f0e"  # Event markers color
    threshold: "#d62728"  # Threshold line color
    on: "#2ca02c"  # On event color (green)
    off: "#9467bd"  # Off event color (purple)
  histogram:
    bins: 50  # Number of histogram bins
    alpha: 0.7  # Histogram transparency

# Logging
logging:
  level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "nilm_ha.log"  # Log file path
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
